name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  MY_VAR:
    description: "My var to greet ppl"
    required: true
    default: "LOL"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "red"
